package Mensagens;

public enum TipoMensagem {
     REGISTO_EVENTO,
     QUERY_INFORMACAO_1,
     QUERY_INFORMACAO_2,
     QUERY_INFORMACAO_3,
     QUERY_INFORMACAO_4,
     QUERY_FILTRO,
     QUERY_OCORRENCIAS_SIMULTANEAS,
     QUERY_OCORRENCIAS_CONSECUTIVAS,
     LOGIN,
     LOGOUT,
     QUERY_INFORMACAO_1_RESPOSTA,
     QUERY_INFORMACAO_2_RESPOSTA,
     QUERY_INFORMACAO_3_RESPOSTA,
     QUERY_INFORMACAO_4_RESPOSTA,
     QUERY_FILTRO_RESPOSTA,
     QUERY_OCORRENCIAS_SIMULTANEAS_RESPOSTA,
     QUERY_OCORRENCIAS_CONSECUTIVAS_RESPOSTA
}